spring:
  application:
    name: lotto
  elastic:
    url: 116.37.91.221:9200
  datasource:
    url: jdbc:mysql://116.37.91.221:3306/lotto?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: niscom
    password: niscom
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enabled: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: always # 초기화 스크립트 사용 여부

  jwt:
    secret: secretlottoabcdjwtauthenticationverylongsecuresecretkeyforhs512algorithmsecretlottoabcdjwtauthenticationverylongsecuresecretkeyforhs512algorithm

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace # SQL 파라미터까지 출력
    org.springframework.web: DEBUG

server:
  port: 8080

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: false
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true