name: CI/CD for Lotto Project

on:
  push:
    branches:
      - develop # develop 브랜치에서만 동작

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 코드
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t seungury/lotto-was:develop .
          docker push seungury/lotto-was:develop

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1. SSH 접속
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 43.202.143.119
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull seungury/lotto-was:develop
            docker stop lotto-app || true
            docker rm lotto-app || true
            docker run -d --name lotto-app -p 8080:8080 seungury/lotto-was:develop
